export const siteConfig = {
  title:
    'Kaushal Chaudhary | Best Freelancer | Front-End Engineer | MERN/MEVN Stack Dev | Full Stack Web Developer | React-Native Developer',
  description:
    'Hi there! My name isKaushal Chaudhary and I am a programmer with a passion for learning and exploring new technologies. With a strong background in full-stack development, I have a well-rounded skill set and am always looking to expand my knowledge and take on new challenges. As a dedicated and driven individual, I am constantly seeking out opportunities to grow and improve as a programmer.',
  keywords: [
    'Kaushal Chaudhary projects',
    'Projects by Kaushal Chaudhary',
    'Kaushal Chaudhary',
    'Contact Kaushal Chaudhary',
    'Projects of Kaushal Chaudhary',
    'Best Freelancer Near me',
    'Affordable Freelancer Near me',
    'Hourly based paid freelancer near me',
    'React.js Developer Near me',
    'Next.js Developer Near me',
    'Best Freelancer',
    'Front-End Engineer',
    'Freelance web development',
    'React-Native development services',
    'Web development portfolio',
    'Kaushal Chaudhary portfolio',
    'Freelancer services',
    'Who isKaushal Chaudhary?',
    'Where doesKaushal Chaudhary Live?',
    'Web Developer Near me',
    'Front-End Developer near me',
    'Top-rated freelancer',
    'Expert web developer',
    'Skilled React-Native Developer',
    'Professional MERN/MEVN Stack Developer',
    'Exceptional Full Stack Web Developer',
    'Local freelance talent',
    'Outstanding Front-End Engineer',
    'Best web development services',
    'Reliable freelance developer',
    'Talented React-Native specialist',
    'TypeScript Developer',
    'JavaScript Developer',
    'UI/UX Design',
    'Responsive Design',
    'Remote Developer',
    'Portfolio',
    'Website Development',
    'Web Applications',
    'Tailwind CSS',
    'GitHub',
    'Vercel',
    'Netlify',
    'India',
    'Available for Hire',
    'Open Source Contributor',
    'Remote Developer India',
    'India Freelancer',
    'Indian Full Stack Developer',
    'International Freelancer',
    'Global Web Developer',
    'Remote Work India',
    'International Remote Developer India',
  ],
  url: 'https://yashkapure.netlify.app',
  defaultLocale: 'en',
};
